### ISSUE TITLE
Refactor Weeks: Priorities.

### ISSUE THREAD

**Issue by FarahZaqout** [FACG5/Twig#284]
## Priority 1:
* [ ] For Monday, we should do a technical spike on how to capture Audio and Video directly from the browser. [Use this link for reference](https://developers.google.com/web/fundamentals/media/recording-audio/). And if it's possible. (t-1d).

This one is very important for user experience. Most users explicitly said that they don't want to record then upload.

## Small (but important) tasks:
* [ ] Fixing all remaining spelling errors mentioned in the issues #176 and #276. (t-4h).
* [ ] Clicking outside the popup modal will trigger the closeModal function. (t-2h).
* [ ] Translation modal will also show the question. (t-1h).
* [ ] Sort languages and dialects in the registration. (t-2h).
* [ ] A Back question on each view. (t-2h).
* [ ] Change the type of input in job title from radio to checkbox. (t-1h).
* [ ] Add "other" option to the job titles (t-2h).
* [ ] Add pre-medical student option in the job titles (for people from the US). (t-1h).
* [ ] Briefly describe in the signup process that the main language of the website is English and add "Which language would you like to translate into" above the "select language" list. (t-1h).
* [ ] Store text in the text translation in the local storage. If the user clicks Audio, then back to text, get the text value from the local storage and assign its value to the text area. (t-2h).
* [ ] hovering the "describe your translation" in the audio/video modals should show a text: "Please let us know if this translation is literal, or if there are some changes you've made, and why these changes make sense if so." (t-2h).
* [ ] When displaying the number of translations, show only translations for the user's dialect. (t-3h).
* [ ] When adding a translation, make the question a larger font, possibly also in red to attract attention. (t-1h).
* [ ] Add a confirm password field to the signup process (t-2h).

## Refactors:
* [ ] Fix responsive design (refer to Makram's Screenshot). (t-1d).
* [ ] Users can select multiple languages and dialects. (t-6h).
* [ ] Allow a question to be assigned multiple specializations (t-6h). This is so we can use it as a tag and display it over multiple specialization (feedback from a doctor was that many questions belong in multiple categories).
* [ ] Allow upvote/downvote action to also add a comment on why it's an upvote or a downvote. (t-6h).
* [ ] Allow the user to edit their own questions in case they made a mistake (t-4h).
* [ ] Add buttons on the question tag to view translations. (I will edit figma and see if you think it's more user friendly).
* [ ] Home page will include links to "what can you do on Twig". #171 (t-1d).

## Adding features:
* [ ] Home page includes a brief description about Twig #177. (t-2h).
* [ ] Navigation bar on all views that links to all website views. (t-4h).
* [ ] Add FAQ view (recycling the question card with very small modification). #157 (t-5h).
* [ ] Add search functionality for: specializations, questions, translations. (t-5h).

**Comment by ali-7** [comment]
add **[Finished]** tag to the finished task

**Comment by FarahZaqout** [comment]
Over the next two weeks:

Initially, we will be doing all the small tasks that have a **P1** next to them. 
From the refactor, we will do all the **P1** tasks as well.
In the add Feature, we will do the what you can do on Twig.

By the end of each day, I will go over the application from start to finish, and make sure the experience is smooth and error free. 

If all the above is done and well tested, We will assess what time we have and what we can do within that timeframe.

@db626 Please if you disagree with the prioritization let us know. We will adjust our plans accordingly.

**Comment by db626** [comment]
Hello Farah!

Will we need our testers from the last round of testing at the end of the
process?

I'm wondering how much to share with them about where we're going...

Bradley.

**Comment by db626** [comment]
Ok. 

I've looked at the in-app recording functions, and for the first time in 14 days, I breathed a sigh of relief.

Your priorities look great Farah.

Let me say: we spoke to many, many programmers before finding Founders & Coders. Some were private programmers, some were PhD students, some worked for big companies (Qualcomm, Facebook). We asked them how long they thought it would take a single programmer to finish this project. They said it would take a single, experienced programmer 7-14 days to complete a project like this. 

I am aware that talking to people about programming and actually selecting someone (or a team) is different. I'm happy that I've gone with Gaza Sky Geeks, because I know that rather than just trusting one person, there's a group with good supervision and quality code. So I'm happy so far with the choice I've made. However I was hoping that the rather strange list (audio recording, etc) of demands for this project would be do-able for GSG in the time given.

I'm happy Max (or whoever runs things) has given us the maximum number of days possible to finish.

As you know, I've dropped the idea of forums, and also badges or reinforcement for participating.

HOWEVER, it's difficult to reduce my needs further.

Any more changes either compromises the product (I do need a lot of information from volunteers about language capability, location, patients, etc) OR makes it too similar to products already on the market (reducing the number of languages, not doing audio, etc).

So whatever we don't finish in this sprint the charity will have to pay to finish. 

So... if things get desperate toward the end what would I prioritize? Rather than tasks, I'd say don't spend a lot of time learning how to do 'new' things for you... of we get into a new panic situation PLEASE spend time wisely doing things you're already good at or know how to do.

I'm hoping it won't get to that and we'll just get everything done.

Programmers, THANK YOU for your work.

**Comment by FarahZaqout** [comment]
There are a few points that we might not have been clear about.

1- The ones who work on the projects are students who only started their learning journey 6 months ago. They are no PhD and no Facebook employees. The students have worked all four weekends, and have often worked until 3AM. Please appreciate that. Reading the first few paragraphs was very disheartening to them.
2- Some of the things on the list above might require learning new things. This includes doing the longitude and latitude.
3- The refactor weeks were originally intended to only polish what already exists. This is me going out of my way and taking full responsibility for that, we have your needs foremost in our mind as we work. However, the fact that these are projects done by students will just be a limiting factor.

**Comment by db626** [comment]
Farah excellent excellent point. I would not want anyone to be disheartened
and am very very sorry if I offended.

The process is not massively transparent to product owners, and I didn’t
know programmers had been working till 3am!

I don’t know much about GSG working policies (is it 9-5, m-f, weekends too,
are you still attending courses while coding, ? Etc)

I am sure that some of the time estimates we received from other coders
were rosy (presumably they can use shortcuts, templates, and presumably
they’ll count on the fact they’ll be doing maintenance too- so no real
‘delivery’ date)... because the project is infinite.

It was a misguided and wrong way to say that I’d tried to measure how
(im)possibile the task I’d given you is before getting to you.

A better way than comparing F&C or GSG to anyone else would be to say that
i was hoping that someone would have said at the start of the process
whether what I’ve asked is technically out of the scope of the time we’ve
got or technically feasible.

When you (Farah) told me that latitude/longitude would take 2 days to
program, it was the first time someone had associated a time estimate
(which is sort of similar to a difficulty level for me) to *anything*
task-wise... and that includes not only our time together but the whole F&C
submission process.

It was helpful.

Of course you may not know how difficult things are or how long things will
take until you get there.

But I would be mortified if I thought I’d given you a task that wasn’t
possible.

I’ve seen other F&C final projects, and some seem easier than others. It’s
hard to know what I’m asking of you.

I also forget that programmers are not only technical people, but creatives.

Please know that if I could be with all of you for every hour of your
programming armed with pizza and tea (It’s all I know how to do- I’m not a
programmer) I would be.

I would choose this path again if given the chance. I’d choose this group.

Please focus on writing quality code, that’s all, and however things go, we
sink or swim together.

We have an expression in English ‘all you can do is your best, and your
best is good enough’.

Apologies again.

**Comment by FarahZaqout** [comment]
Thanks Bradley. 

About the 3AM part and working weekends, the team were doing it voluntarily, against the GSG policy, because they see how passionate you are, and they honestly think the idea of Twig is something worth pouring their hearts and souls into. they understand that you care very deeply about the product and want to deliver as much as possible to you, but again, the students basically had to learn the framework they're using to develop the product as they built it. (This project is actually the final stage of the course itself).

Estimating time both from FAC and during the actual work is something GSG and I should have done better. I apologize for that, but I guarantee you that out of all the FAC cohorts, current and previous, from all campuses, this team is among the best students.

We will give you our absolute best, and we will finish as many tasks as possible. 

I just want you to know that there was no mistake on your part. If something was unclear to you, the fault is mine as it is my responsibility to make everything clear.

We will try to make the final outcome as viable as possible.

Again thank you for understanding.
