### ISSUE TITLE
Api endpoints

### ISSUE THREAD

**Issue by HemaSAli** [FACG5/Twig#91]
### API endpoints

- /signup
  - [x] POST method - user can sign up to the site by entering his data
###
- /login
  - [x] POST method -  user can sign in to the site by email and password
###
- /logout
  - [x] Get method -  user can log out from the site
###
- /details 
   - [x] GET method - get user data for profile card #184 
###
- /profile
   - [x] GET method - get user data  #197
   - [ ] PUT method - edit data of user
   - [ ] DELETE method - delete profile
###
- /specialization
   - [x] GET method - get specializations list #160
###
- /specialization/question/:specializationId
   - [x] post method - post questions of specialization #245
###
- /specialization/:section
   - [x] GET method - get questions of specialization by section #151
###
- /languages
   - [x] GET method - get list of languages
###
-  /dialects/:languageId
   - [x] GET method - get list of dialects by language id
###
###
- /questions/:questionId
   - [x] GET method - get translations of question by id of question as param
   - [x] POST method - post translations for question
###
-  /questions/:questionId/voteup
   - [x] POST method - vote up the translation of question
###
- /questions/:questionId/votedown
   - [x] POST method - vote down the translation of question
###
Videos and Audios
- /files/:link
   - [x] GET method - get link of videos and audios from database
###
Statistics
- /statistics
- [x] GET method - get statistics for homepage #338

**Comment by FarahZaqout** [comment]
edit data of user should use ```PUT``` method.

**Comment by HemaSAli** [comment]
> edit data of user should use `PUT` method. @HemaSAli

Done ,
